// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcfymntfwlighngddesb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjZnltbnRmd2xpZ2huZ2RkZXNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3OTIyODAsImV4cCI6MjA3MTM2ODI4MH0.PWAfWH0CiWj3gJesPT8Jnd13nRY32aOqMdho5ouHQtI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});